### ISSUE TITLE
org.havenask.engine.util.testCleanVersionPublishFiles偶尔跑失败

### ISSUE THREAD

**Issue by Huaixinww** [alibaba/havenask-federation#395]
```
org.havenask.engine.util.UtilsTests > testCleanVersionPublishFiles FAILED
    java.lang.AssertionError: expected:<2> but was:<3>
        at __randomizedtesting.SeedInfo.seed([A1A658E264755312:61837A0725F020B4]:0)
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:647)
        at org.junit.Assert.assertEquals(Assert.java:633)
        at org.havenask.engine.util.UtilsTests.testCleanVersionPublishFiles(UtilsTests.java:245)
REPRODUCE WITH: ./gradlew ':modules:havenask-engine:test' --tests "org.havenask.engine.util.UtilsTests.testCleanVersionPublishFiles" -Dtests.seed=A1A658E264755312 -Dtests.security.manager=false -Dtests.jvm.argline="-XX:TieredStopAtLevel=1" -Dtests.locale=sk-SK -Dtests.timezone=CTT -Druntime.java=11
```
跑了一下发现有时候会多一个extra0文件导致stream.count()变成3

**Comment by Huaixinww** [comment]
fixed by:https://github.com/alibaba/havenask-federation/pull/396
