### ISSUE TITLE
启动时，MetaDataSyncer偶尔会出现如下NPE

### ISSUE THREAD

**Issue by weizijun** [alibaba/havenask-federation#439]
```
[2024-02-02T17:51:23,258][INFO ][o.h.n.Node               ] [l57a12214.sqa.nu8] started
[2024-02-02T17:51:23,305][ERROR][o.h.e.MetaDataSyncer     ] [l57a12214.sqa.nu8] error when update qrs target:
java.lang.NullPointerException: null
	at org.havenask.engine.MetaDataSyncer.isHavenaskIndexChanged(MetaDataSyncer.java:646) ~[havenask-engine-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at org.havenask.engine.MetaDataSyncer.shouldUpdateQrs(MetaDataSyncer.java:346) ~[havenask-engine-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at org.havenask.engine.MetaDataSyncer.applyClusterState(MetaDataSyncer.java:335) [havenask-engine-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at org.havenask.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:530) [havenask-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at org.havenask.cluster.service.ClusterApplierService.callClusterStateAppliers(ClusterApplierService.java:521) [havenask-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at org.havenask.cluster.service.ClusterApplierService.applyChanges(ClusterApplierService.java:491) [havenask-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at org.havenask.cluster.service.ClusterApplierService.runTask(ClusterApplierService.java:438) [havenask-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at org.havenask.cluster.service.ClusterApplierService.access$000(ClusterApplierService.java:88) [havenask-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at org.havenask.cluster.service.ClusterApplierService$UpdateTask.run(ClusterApplierService.java:182) [havenask-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at org.havenask.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:704) [havenask-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at org.havenask.common.util.concurrent.PrioritizedHavenaskThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedHavenaskThreadPoolExecutor.java:273) [havenask-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at org.havenask.common.util.concurrent.PrioritizedHavenaskThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedHavenaskThreadPoolExecutor.java:236) [havenask-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by Huaixinww** [comment]
暂时没有复现出这个问题，待后续跟进
