### ISSUE TITLE
测试多向量case时，MetaDataSyncer偶尔会出现NPE

### ISSUE THREAD

**Issue by Huaixinww** [alibaba/havenask-federation#440]
报错信息如下：
```
[2024-02-04T10:19:02,026][INFO ][o.h.e.u.Utils            ] [l57a12214.sqa.nu8] directory [/usr/share/havenask/data/havenask/runtimedata/multi_vector_test/generation_0/partition_0_13107] does not exist or the version num is too big
[2024-02-04T10:19:02,026][ERROR][o.h.e.MetaDataSyncer     ] [l57a12214.sqa.nu8] update searcher heartbeat target failed
java.lang.NullPointerException: null
        at java.util.regex.Matcher.getTextLength(Matcher.java:1770) ~[?:?]
        at java.util.regex.Matcher.reset(Matcher.java:416) ~[?:?]
        at java.util.regex.Matcher.<init>(Matcher.java:253) ~[?:?]
        at java.util.regex.Pattern.matcher(Pattern.java:1133) ~[?:?]
        at org.havenask.engine.MetaDataSyncer.extractIncVersion(MetaDataSyncer.java:521) ~[havenask-engine-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.havenask.engine.MetaDataSyncer.lambda$createSearcherUpdateHeartbeatTargetRequest$0(MetaDataSyncer.java:501) ~[havenask-engine-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
        at org.havenask.engine.MetaDataSyncer.createSearcherUpdateHeartbeatTargetRequest(MetaDataSyncer.java:496) ~[havenask-engine-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.havenask.engine.MetaDataSyncer$SyncTask.runInternal(MetaDataSyncer.java:248) [havenask-engine-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.havenask.common.util.concurrent.AbstractAsyncTask.run(AbstractAsyncTask.java:164) [havenask-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at org.havenask.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:704) [havenask-1.0.0-SNAPSHOT.jar:1.0.0-SNAPSHOT]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by Huaixinww** [comment]
fixed by:https://github.com/alibaba/havenask-federation/pull/441
