### ISSUE TITLE
reindex远端es失败问题

### ISSUE THREAD

**Issue by supercocoa** [alibaba/havenask-federation#484]
按照文档从远端es reindex了一个es索引，fed的dashboards里可以看到这个es索引，但是执行ha3查询找不到，这个大概是啥问题？
```sh
POST _reindex
{
  "source": {
    "remote": {
      "host": "http://xxx:9200",
      "username": "xxx",
      "password": "xxx"
    },
    "index": "test_es"
  },
  "dest": {
    "index": "test_ha3"
  }
}

GET _cat/indices
green open test_ha3                      n1uW2iPmTc65hQqgti5ALw 1 1 177 0 217.4kb 116.2kb
```

```sh
GET /_havenask/sql?query=select * from test_ha3
```

```log
USE_TIME: 4.91ms, ROW_COUNT: 0, HAS_SOFT_FAILURE: 0, SOFT_FAILURE_CODES: [], COVERAGE: 1
failed to get sql plan, error message is : [IQUAN_EC_INTERNAL_ERROR] internal error : From line 1, column 15 to line 1, column 22: Object 'test_ha3' not found
Object 'test_ha3' not found
org.apache.calcite.runtime.CalciteContextException: From line 1, column 15 to line 1, column 22: Object 'test_ha3' not found
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.apache.calcite.runtime.Resources$ExInstWithCause.ex(Resources.java:505)
	at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:945)
	at org.apache.calcite.sql.SqlUtil.newContextException(SqlUtil.java:930)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.newValidationError(SqlValidatorImpl.java:5425)
	at org.apache.calcite.sql.validate.IdentifierNamespace.resolveImpl(IdentifierNamespace.java:183)
	at org.apache.calcite.sql.validate.IdentifierNamespace.validateImpl(IdentifierNamespace.java:188)
	at org.apache.calcite.sql.validate.AbstractNamespace.validate(AbstractNamespace.java:88)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateNamespace(SqlValidatorImpl.java:1131)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateQuery(SqlValidatorImpl.java:1102)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateFrom(SqlValidatorImpl.java:3415)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateFrom(SqlValidatorImpl.java:3394)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateSelect(SqlValidatorImpl.java:3751)
	at org.apache.calcite.sql.validate.SelectNamespace.validateImpl(SelectNamespace.java:61)
	at org.apache.calcite.sql.validate.AbstractNamespace.validate(AbstractNamespace.java:88)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateNamespace(SqlValidatorImpl.java:1131)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateQuery(SqlValidatorImpl.java:1102)
	at org.apache.calcite.sql.SqlSelect.validate(SqlSelect.java:248)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validateScopedExpression(SqlValidatorImpl.java:1077)
	at org.apache.calcite.sql.validate.SqlValidatorImpl.validate(SqlValidatorImpl.java:783)
	at com.taobao.search.iquan.core.api.impl.IquanExecutorFactory$Executor.validate(IquanExecutorFactory.java:219)
	at com.taobao.search.iquan.core.api.impl.SqlQueryableImpl$SqlWorkFlow.validateSql(SqlQueryableImpl.java:391)
	at com.taobao.search.iquan.core.api.impl.SqlQueryableImpl$SqlWorkFlow.process(SqlQueryableImpl.java:286)
	at com.taobao.search.iquan.core.api.impl.SqlQueryableImpl.select(SqlQueryableImpl.java:81)
	at com.taobao.search.iquan.client.common.service.SqlQueryService.sqlQuery(SqlQueryService.java:89)
	at com.taobao.search.iquan.client.IquanClient.sqlQuery(IquanClient.java:61)
Caused by: org.apache.calcite.sql.validate.SqlValidatorException: Object 'test_ha3' not found
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.apache.calcite.runtime.Resources$ExInstWithCause.ex(Resources.java:505)
	at org.apache.calcite.runtime.Resources$ExInst.ex(Resources.java:599)
	... 24 more


------------------------------- PLAN INFO ---------------------------
SQL QUERY:
query=select * from test_ha3&&kvpair=databaseName:general
IQUAN_RESULT:
{"error_code":0,"error_message":"","result":{"rel_plan_version":"","rel_plan":[],"exec_params":{}}}

------------------------------- TRACE INFO ---------------------------

```

**Comment by weizijun** [comment]
在本地是否已经提前创建好test_ha3索引：
```
PUT test_ha3
{
    "settings": {
        "index.engine": "havenask"
    },
    "mappings": {
        "properties": {
            "foo": {
                "type": "keyword"
            }
        }
    }
}
```

可以看下本地test_ha3索引的settings，是否包含`"index.engine": "havenask"`，来确认test_ha3是havenask索引

**Comment by supercocoa** [comment]
不好意思，没看到要先提前创建索引，创建ha3索引后可以了
