### ISSUE TITLE
debug模式下，执行sql会导致fed抛异常

### ISSUE THREAD

**Issue by Huaixinww** [alibaba/havenask-federation#514]
具体报错如下：
```
» fatal error in thread [havenask[runTask-0][search][T#5]], exiting
»  java.lang.AssertionError: callers should ensure the XContentBuilder is closed themselves
»       at org.havenask.rest.action.RestBuilderListener.assertBuilderClosed(RestBuilderListener.java:72)
»       at org.havenask.rest.action.RestBuilderListener.buildResponse(RestBuilderListener.java:59)
»       at org.havenask.rest.action.RestResponseListener.processResponse(RestResponseListener.java:57)
»       at org.havenask.rest.action.RestActionListener.onResponse(RestActionListener.java:67)
»       at org.havenask.action.support.TransportAction$1.onResponse(TransportAction.java:109)
»       at org.havenask.action.support.TransportAction$1.onResponse(TransportAction.java:103)
»       at org.havenask.engine.search.action.TransportHavenaskSqlAction.lambda$doExecute$0(TransportHavenaskSqlAction.java:71)
»       at org.havenask.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:64)
»       at org.havenask.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:763)
»       at org.havenask.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:57)
»       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
»       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
»       at java.base/java.lang.Thread.run(Thread.java:834)

> Task :run FAILED

FAILURE: Build failed with an exception.
```

**Comment by Huaixinww** [comment]
RestHavenaskSqlAction重写了`buildResponse(Response response, XContentBuilder builder)`方法，注释中说明了`Implementors should ensure that they close the provide`，之前RestHavenaskSqlAction没有正确close XContentBuilder导致这个异常。实际上即使实现类没有正确close XContentBuilder，这个类的try-with-resources语句也能保证XContentBuilder最终都会被正确关闭。
```
@Override
    public final RestResponse buildResponse(Response response) throws Exception {
        try (XContentBuilder builder = channel.newBuilder()) {
            final RestResponse restResponse = buildResponse(response, builder);
            assert assertBuilderClosed(builder);
            return restResponse;
        }
    }

    /**
     * Builds a response to send back over the channel. Implementors should ensure that they close the provided {@link XContentBuilder}
     * using the {@link XContentBuilder#close()} method.
     */
    public abstract RestResponse buildResponse(Response response, XContentBuilder builder) throws Exception;
```
